/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EndingRouteImport } from './routes/ending'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GamesRouteImport } from './routes/games'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MusicRouteImport } from './routes/music'
import { Route as ScratchRouteImport } from './routes/scratch'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WishesRouteImport } from './routes/wishes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndingRoute = EndingRouteImport.update({
  id: '/ending',
  path: '/ending',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchRoute = ScratchRouteImport.update({
  id: '/scratch',
  path: '/scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WishesRoute = WishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ending': typeof EndingRoute
  '/gallery': typeof GalleryRoute
  '/games': typeof GamesRoute
  '/home': typeof HomeRoute
  '/letters': typeof LettersRoute
  '/memories': typeof MemoriesRoute
  '/music': typeof MusicRoute
  '/scratch': typeof ScratchRoute
  '/timeline': typeof TimelineRoute
  '/wishes': typeof WishesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ending': typeof EndingRoute
  '/gallery': typeof GalleryRoute
  '/games': typeof GamesRoute
  '/home': typeof HomeRoute
  '/letters': typeof LettersRoute
  '/memories': typeof MemoriesRoute
  '/music': typeof MusicRoute
  '/scratch': typeof ScratchRoute
  '/timeline': typeof TimelineRoute
  '/wishes': typeof WishesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ending': typeof EndingRoute
  '/gallery': typeof GalleryRoute
  '/games': typeof GamesRoute
  '/home': typeof HomeRoute
  '/letters': typeof LettersRoute
  '/memories': typeof MemoriesRoute
  '/music': typeof MusicRoute
  '/scratch': typeof ScratchRoute
  '/timeline': typeof TimelineRoute
  '/wishes': typeof WishesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ending'
    | '/gallery'
    | '/games'
    | '/home'
    | '/letters'
    | '/memories'
    | '/music'
    | '/scratch'
    | '/timeline'
    | '/wishes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ending'
    | '/gallery'
    | '/games'
    | '/home'
    | '/letters'
    | '/memories'
    | '/music'
    | '/scratch'
    | '/timeline'
    | '/wishes'
  id:
    | '__root__'
    | '/'
    | '/ending'
    | '/gallery'
    | '/games'
    | '/home'
    | '/letters'
    | '/memories'
    | '/music'
    | '/scratch'
    | '/timeline'
    | '/wishes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndingRoute: typeof EndingRoute
  GalleryRoute: typeof GalleryRoute
  GamesRoute: typeof GamesRoute
  HomeRoute: typeof HomeRoute
  LettersRoute: typeof LettersRoute
  MemoriesRoute: typeof MemoriesRoute
  MusicRoute: typeof MusicRoute
  ScratchRoute: typeof ScratchRoute
  TimelineRoute: typeof TimelineRoute
  WishesRoute: typeof WishesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ending': {
      id: '/ending'
      path: '/ending'
      fullPath: '/ending'
      preLoaderRoute: typeof EndingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratch': {
      id: '/scratch'
      path: '/scratch'
      fullPath: '/scratch'
      preLoaderRoute: typeof ScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishes': {
      id: '/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof WishesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndingRoute: EndingRoute,
  GalleryRoute: GalleryRoute,
  GamesRoute: GamesRoute,
  HomeRoute: HomeRoute,
  LettersRoute: LettersRoute,
  MemoriesRoute: MemoriesRoute,
  MusicRoute: MusicRoute,
  ScratchRoute: ScratchRoute,
  TimelineRoute: TimelineRoute,
  WishesRoute: WishesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
